spring:
  datasource:
    url: jdbc:h2:mem:collegedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  data:
    file-path: /tmp/college-data.json
    import-on-startup: true
  student:
    file-path: /tmp/student-data.json
    import-on-startup: true

server:
  port: 8080

logging:
  level:
    com.example: DEBUG
