spring:
  datasource:
    url: "jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-mumbai-1.oraclecloud.com))(connect_data=(service_name=gef21c404a80654_aahzidevdb_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))"
    driver-class-name: oracle.jdbc.OracleDriver
    username: APP_PROD
    password: "Aahzi_Prod_2026!"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

app:
  data:
    #file-path: /tmp/college-data.json
    file-path: ./dataOnLoad/college-data.json
    import-on-startup: false
  student:
    #file-path: /tmp/student-data.json
    file-path: ./dataOnLoad/student-data.json
    import-on-startup: false
  admission:
    base-path: dataOnLoad/
    import-on-startup: true
  cutoffAllotment:
    #file-path: data/cutoff_analysis.json
    file-path: dataOnLoad/CutoffanalysisBasedOnAllotment2025.json
    import-on-startup: true
  college-details:
    file-path: dataOnLoad/CollegeDetails.json
    import-on-startup: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.aahzi: DEBUG
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: ./logs/college-app.log