spring:
  datasource:
    url: jdbc:h2:mem:collegedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  data:
    #file-path: /tmp/college-data.json
    file-path: ./dataOnLoad/college-data.json
    import-on-startup: false
  student:
    #file-path: /tmp/student-data.json
    file-path: ./dataOnLoad/student-data.json
    import-on-startup: false
  admission:
    base-path: dataOnLoad/
    import-on-startup: true
  cutoffAllotment:
    #file-path: data/cutoff_analysis.json
    file-path: dataOnLoad/CutoffanalysisBasedOnAllotment2025.json
    import-on-startup: true
  college-details:
    file-path: dataOnLoad/CollegeDetails.json
    import-on-startup: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.aahzi: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: logs/college-app.log